name: luzo_interview
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


############ Core ############  
  cupertino_icons: ^1.0.8

############ Ui dependencies ############
  carousel_slider: ^5.0.0
  lottie: ^3.3.1
  google_fonts: ^6.2.1

############ Utils ############
  device_preview: ^1.2.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/image1.png
